### ISSUE TITLE
1.9.0 to 1.10.0 is missing remapped property values

### ISSUE THREAD

**Issue by KCodeYT** [pmmp/BedrockBlockUpgradeSchema#1]
`facing_direction_00` is missing index for old value 5

**Comment by dktapps** [comment]
Old value 5 would be east, I don't see what's to remap ...

**Comment by dktapps** [comment]
I'll also point out that these schemas have been generated and fully battle tested using [pmmp/BedrockBlockPaletteArchive](https://github.com/pmmp/BedrockBlockPaletteArchive) and palette mappings generated from vanilla. The mapping results are **at least** as correct as Bedrock itself.

**Comment by KCodeYT** [comment]
But the [1.10.0.nbt](https://github.com/pmmp/BedrockBlockPaletteArchive/blob/master/1.10.0.nbt) does not contain for example:
```json
{
  "name": "minecraft:smoker",
  "states": {
    "direction": 5
  },
  "version": 17432626
}
```

**Comment by dktapps** [comment]
Hmm, you're correct. Then I suppose that's a conversion error in Bedrock itself.

I vaguely remember encountering something like this during testing. As I recall, they changed the property from `facing_direction` to `direction`, and then back to `facing_direction` in some version later than that.

**Comment by KCodeYT** [comment]
Hmm yea from 1.9 to 1.10 its renamed to direction and then from 1.10 to 1.12 back to facing_direction

**Comment by KCodeYT** [comment]
Hmm yea, everything works fine when upgrading from 1.9 to 1.12, except this causes blocks to lose their `facing_direction` values.

**Comment by dktapps** [comment]
The appropriate mapping for 1.9 -> 1.10 should probably be something like:

0 => 2 (down -> north)
1 => 2 (up -> north)
2 => 2 (north) (can omit this, since it's the same)
3 => 0 (south)
4 => 1 (west)
5 => 3 (east)
6 => 2 (invalid -> north)
7 => 2 (invalid -> north)

and then for 1.10 -> 1.12 the mapping is already correct.
