### ISSUE TITLE
Bell is missing direction property

### ISSUE THREAD

**Issue by RaphiMC** [pmmp/BedrockBlockUpgradeSchema#7]
When running the minecraft:bell through all schemas starting from the first the resulting block state is invalid because it is missing the direction property. The attachment and toggle_bit were added properly.

**Comment by dktapps** [comment]
I don't think that property was ever altered. This library doesn't include stuff that existed when the blockstate was originally added.

It sounds to me like you have a bad output from a third party converter. These schemas have been tested against the corresponding palettes to ensure the outputs are valid, so the only way for this to happen is if the given blockstate was invalid to begin with.

**Comment by RaphiMC** [comment]
Yeah you are right. My input blockstate was already invalid to begin with. It should have had the direction property. Sorry for wasting your time

**Comment by dktapps** [comment]
That's fine, happens to the best of us :)
